#!/bin/bash
# Interactive installer for TUI applications
# Generated by scripts/generate-installer.py
# Compatible with bash 3.x (macOS default)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get the absolute path of this repo
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== TUI Application Installer ==="
echo "Repo: $REPO_DIR"
echo
# Single app installation
SELECTED_APPS="prototui"
echo "Will install: prototui"
echo "  ProtoTUI development tools (skill sync, installer generator)"
echo


# Ask about auto-update
echo
read -p "Enable auto-update on launch? (y/n) [n]: " AUTO_UPDATE
AUTO_UPDATE=${AUTO_UPDATE:-n}

# Ask about install location
echo
read -p "Install commands to which directory? [~/bin]: " INSTALL_DIR
INSTALL_DIR=${INSTALL_DIR:-~/bin}
INSTALL_DIR=$(eval echo "$INSTALL_DIR")  # Expand ~

# Create install directory if needed
mkdir -p "$INSTALL_DIR"

echo
echo "Installing selected apps..."
echo


# Install prototui
if true; then
    cat > "$INSTALL_DIR/prototui" <<'WRAPPER_EOF'
#!/bin/bash
# Auto-generated wrapper for prototui
# Repo: REPO_DIR_PLACEHOLDER

REPO_DIR="REPO_DIR_PLACEHOLDER"
VENV_DIR="$REPO_DIR/.venv"

# Auto-update (configured during install)
AUTO_UPDATE_PLACEHOLDER

# Setup venv if missing (first run)
if [ ! -d "$VENV_DIR" ]; then
    echo "First run: Setting up environment..." >&2
    python3 -m venv "$VENV_DIR"
    "$VENV_DIR/bin/pip" install -q -e "$REPO_DIR"
fi

# Check if dependencies need updating
if [ "$REPO_DIR/pyproject.toml" -nt "$VENV_DIR/.installed" ]; then
    echo "Updating dependencies..." >&2
    "$VENV_DIR/bin/pip" install -q -e "$REPO_DIR"
    touch "$VENV_DIR/.installed"
fi

# Run the app
"$VENV_DIR/bin/python" -c "from tui.prototui.main import main; main()" "$@"
WRAPPER_EOF

    # Replace placeholders
    sed -i.bak "s|REPO_DIR_PLACEHOLDER|$REPO_DIR|g" "$INSTALL_DIR/prototui"

    if [[ "$AUTO_UPDATE" == "y" ]]; then
        sed -i.bak "s|AUTO_UPDATE_PLACEHOLDER|cd \"\$REPO_DIR\" \&\& git pull -q 2>/dev/null \|\| true|" "$INSTALL_DIR/prototui"
    else
        sed -i.bak "s|AUTO_UPDATE_PLACEHOLDER|# Auto-update disabled|" "$INSTALL_DIR/prototui"
    fi

    rm -f "$INSTALL_DIR/prototui.bak"
    chmod +x "$INSTALL_DIR/prototui"

    echo "  ✓ Installed prototui"
fi

# Check if install dir is in PATH
if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
    echo
    echo -e "${YELLOW}Warning: $INSTALL_DIR is not in your PATH${NC}"
    echo "Add this to your ~/.zshrc or ~/.bashrc:"
    echo "  export PATH=\"$INSTALL_DIR:\$PATH\""
    echo
fi

echo -e "${GREEN}✓ Installation complete!${NC}"
echo
echo "Installed commands:"
if [[ -n "$SELECTED_APPS" ]]; then
    for app in $SELECTED_APPS; do
        echo "  - $app"
    done
fi
echo
echo "Settings:"
echo "  Auto-update: $AUTO_UPDATE"
echo "  Location: $INSTALL_DIR"
echo
